#!/usr/bin/python3

DOMAIN = "clicky"
PATH = "/usr/share/locale"

import os
import gettext
from mintcommon import additionalfiles

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=clicky
Icon=clicky
Terminal=false
Type=Application
Encoding=UTF-8
Categories=GTK;GNOME;Utility;X-GNOME-Utilities;
Keywords=project;keywords;
StartupNotify=false
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/clicky.desktop", prefix, _("Screenshot"), _("Save images of your screen or individual windows"), suffix)
